name: test
on: [ push, pull_request ]

jobs:
  test:
    name: Run CMake Test ğŸ§ª
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc cmake

      - name: Build and Run 64bit Tests
        run: |
          mkdir build
          cd build
          cmake -DBUILD=test ..
          make
          make test || ctest --rerun-failed --output-on-failure

      - name: Build and Run 32bit Tests
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -DBUILD=test -DFORCE_32BIT=1 ..
          make
          make test || ctest --rerun-failed --output-on-failure
